import './globals.css';
import { Inter } from 'next/font/google';
import NavMenu from "./shared/NavMenu";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Pracitce Next.js 1',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-zinc-900"}>{children}
      <NavMenu />
      </body>
    </html>
  )
}
